CREATE DATABASE IF NOT EXISTS clickfit;
USE clickfit;

CREATE TABLE users (
  ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  type VARCHAR(255) NOT NULL,
  active TINYINT DEFAULT 1
);
